name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-rpn-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build rpn executable
      run: make rpn

  build-run-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build rpn executable
        run: make rpn CC='clang'