name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-rpn:

    runs-on: [ ubuntu-latest, macOS ]

    steps:
    - uses: actions/checkout@v4
    - name: Build rpn executable
      run: make rpn
